=== gobravery/wind/target/classes/tables.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tables (table+,primarycol*,cpkey*)>
<!ELEMENT table (name+,columns+,primarycol*,cpkey*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT primarycol (#PCDATA)>
<!ELEMENT cpkey (#PCDATA)>
<!ELEMENT column (#PCDATA)>
<!ATTLIST column type (String|Integer|Long|DateTime|Clob|Blob|Float|Double|Datestamp) "String">
<!ATTLIST column length CDATA "10">
<!ATTLIST column auto (true|false) "false">

=== gobravery/wind/target/classes/cptables.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tables SYSTEM "./tables.dtd">
  <tables>
  	<table>
  		<name>user</name>
  		<columns>
  			<column type="String">Host</column>
  			<column type="String">User</column>
  			<column type="String">Select_priv</column>
  		</columns>
  		<primarycol>User</primarycol>
  		<cpkey>Select_priv</cpkey>
  	</table>
  	<table>
  		<name>help_keyword</name>
  		<columns>
  			<column type="Integer">help_keyword_id</column>
  			<column type="String">name</column>
  		</columns>
  	</table>
  	<primarycol>help_keyword_id</primarycol>
  	<cpkey>help_keyword_id</cpkey>
  </tables>
